### ISSUE TITLE
Markdown Notebooks - Cannot open empty markdown files

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-markdown-notebook#4]
Testing microsoft/vscode#101325

1.  Create an empty markdown file called test.md
2. Try to open the file in a markdown notebook.
3. Receive the error "Unable to open 'test.md': Cannot read property 'match' of undefined

**Comment by mjbvz** [comment]
@roblourens I confirmed this bug is on this line:

https://github.com/microsoft/vscode-markdown-notebook/blob/5ae117c01ccfcd02a52229691b0a656524611a38/src/markdownParser.ts#L40

`line` is undefined in this case. I took a quick look at the code but wasn't sure if just adding a simple `!!` check was the best fix
